// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7iyKS27bOdOKrOhCnKzMiivKsdI_q_jM',
    appId: '1:103275221661:web:f9a2616f4a5d130a63fa74',
    messagingSenderId: '103275221661',
    projectId: 'mobile-garage-345',
    authDomain: 'mobile-garage-345.firebaseapp.com',
    storageBucket: 'mobile-garage-345.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCMBQLqRDlRw-ka4JZiNX3zDtwIsGGQok',
    appId: '1:103275221661:android:f40284760ce969f263fa74',
    messagingSenderId: '103275221661',
    projectId: 'mobile-garage-345',
    storageBucket: 'mobile-garage-345.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzHM5tDmSFw8Ue3KZpsk9wddr71YMjaG0',
    appId: '1:103275221661:ios:3a3e6b49e982a31863fa74',
    messagingSenderId: '103275221661',
    projectId: 'mobile-garage-345',
    storageBucket: 'mobile-garage-345.appspot.com',
    iosClientId: '103275221661-38jputdn0lh07hbd61jb7alifeek1ah7.apps.googleusercontent.com',
    iosBundleId: 'marcinmiszewski.mobileGarage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzHM5tDmSFw8Ue3KZpsk9wddr71YMjaG0',
    appId: '1:103275221661:ios:3a3e6b49e982a31863fa74',
    messagingSenderId: '103275221661',
    projectId: 'mobile-garage-345',
    storageBucket: 'mobile-garage-345.appspot.com',
    iosClientId: '103275221661-38jputdn0lh07hbd61jb7alifeek1ah7.apps.googleusercontent.com',
    iosBundleId: 'marcinmiszewski.mobileGarage',
  );
}
